export enum ErrorsEnum {
  INVALID_LOGIN_OR_PASSWORD = 'INVALID_LOGIN_OR_PASSWORD',
  INTERNAL_ERROR = 'INTERNAL_ERROR',
  UNAUTHORIZED = 'UNAUTHORIZED',
  USER_ALREADY_EXISTS = 'USER_ALREADY_EXISTS',
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  PASSWORD_MISMATCH = 'PASSWORD_MISMATCH',
  INCORRECT_CURRENT_PASSWORD = 'INCORRECT_CURRENT_PASSWORD',
}
